### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [SvS30/svs-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by salimvzqz** [comment]
Sorry, I've been working on some features.
Can you [check again](https://github.com/SvS30/svs-theme#readme)?

**Comment by unixorn** [comment]
cool, thanks, will add shortly
